default:
	fastjar -cM content/*.* locale/en-US/*.* skin/*.* skin/unix/*.* -f yarip.jar
#	fastjar -cM content/*.* locale/en-US/*.* skin/*.* skin/unix/*.* skin/win/*.* \
#skin/winaero/*.* skin/mac/*.* -f yarip.jar

clean:
	rm -f yarip.jar
